import React, {useEffect, useState} from 'react';
import Header from "./header";
import MovieCard from "../../components/movie-card";
import Heading from "../../components/heading";
import MovieAdd from "../movies/movie-add";
import axios from "axios";
import {useDispatch} from "react-redux";
import {toggleLoader} from "../../redux/actions";

function Home(props) {

    const [movieList, setMovieList] = useState([]);
    const dispatch = useDispatch();

    useEffect(() => {
        dispatch(toggleLoader(true))
        axios.get(`${process.env.REACT_APP_HOST}movie`)
            .then((res) => {
                setMovieList(res.data)
            })
            .catch((err) => {
                console.log(err)
            }).finally(() => {
            dispatch(toggleLoader(false))
        })
    }, []);

    console.log(movieList)

    return (
        <>
            <Header/>
            <div className={"container my-5 py-5"}>
                <div className={"hadding-area my-5"}>
                    <h2 className={"text-white"}>Latest Movies</h2>
                </div>
                <div className={"row"}>
                    {movieList?.slice(0,3).map((movie, index) =>
                        <div className={"col-md-4"} key={"movie" + index}>
                            <MovieCard movie={movie} key={index}/>
                        </div>
                    )}


                </div>

                <Heading heading={"Action Movies"}
                         subTxt={"Key elements of action movies include fast-paced sequences, high-stakes situations, and a focus on physical feats and daring stunts. While action films can be combined with other genres like science fiction, fantasy, or espionage, the primary emphasis is on the excitement generated by the action scenes."}/>
                <div className={"row"}>
                    {movieList.filter((data)=> data.category === "Action")?.slice(0,3).map((movie, index) =>
                        <div className={"col-md-4"} key={"movie" + index}>
                            <MovieCard movie={movie} key={index}/>
                        </div>
                    )}
                </div>
            </div>
        </>
    );
}

export default Home;